<?php

namespace AppBundle\Repository;

/**
 * HobbyPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
