<?php

namespace AppBundle\Repository;

/**
 * ProjectLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
