<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithLimits($limit) {
        $results = $this->createQueryBuilder('p')
            ->select('p.id')
            ->orderBy('p.position', 'asc')
            ->getQuery()
            ->setMaxResults($limit)
            ->getResult();

        $ids = array_map(function($project){
            return $project['id'];
        }, $results);

        return $this->createQueryBuilder('p')
            ->select('p, pdb, pf, pl, pr, pp')
            ->leftJoin('p.projectDatabase', 'pdb')
            ->leftJoin('p.projectFramework', 'pf')
            ->leftJoin('p.projectLanguages', 'pl')
            ->leftJoin('p.projectRole', 'pr')
            ->leftJoin('p.projectPhoto', 'pp')
            ->where('p.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }
}
