<?php

namespace AppBundle\Repository;

/**
 * ProjectDatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDatabaseRepository extends \Doctrine\ORM\EntityRepository
{
}
