<?php

namespace AppBundle\Repository;

/**
 * ProjectPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
